services:
  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build:
      context: ./ewm-stats-service/stats-main-service
      dockerfile: Dockerfile
    image: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ewm-main-service
    image: main-server
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"